version: '3.0'
services:
  api:
    # container_name: node_app
    build: .
    volumes:
      - .:/usr/src/app
    # ports:
    #  - 3000:3000
    networks:
      - backend
  nginx:
    image: nginx
    volumes:
      # - ./conf.d:/etc/nginx/conf.d
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - api
    ports:
      - 3000:3000

networks:
  backend:
    driver: bridge